language: python
env:
  - TEST_DOCTESTS="true"
  - TEST_DOCTESTS="false"
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
matrix:
  include:
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="false"
    - python: 2.7
      env:
        - TEST_THEANO="true"
      virtualenv:
        system_site_packages: true
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="false"
    - python: 2.7
      env: TEST_SPHINX="true"
  allow_failures:
    - python: "pypy"
before_install:
  - if [[ "${TEST_GMPY}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get install libgmp-dev;
      pip install "gmpy==1.16";
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern;
      pip install "sphinx==1.1.3";
    fi
  - if [[ "${TEST_MATPLOTLIB}" == "true" ]]; then
      pip install "numpy==1.7.1"; # NumPy is preinstalled in the travis-ci venvs
      pip install "matplotlib==1.2.1";
    fi
  - if [[ "${TEST_THEANO}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get install python-numpy python-scipy;
      # may need a hack like this
      # ln -s /usr/lib/python2.7/dist-packages/numpy ~/virtualenv/python2.7/lib/python2.7/site-packages/;
      pip install -e git+git@github.com:Theano/Theano.git#egg=Theano;
    fi
install:
  - python setup.py install
script:
  - bin/test_travis.sh
notifications:
  email: false
