# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Doctests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      env:
        TEST_DOCTESTS: "true"

  - script: python -m pip install --upgrade pip && pip install mpmath
    displayName: 'Install dependencies'

  - script: |
      ./bin/test_travis.sh
    displayName: 'doctests'
