# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  conda.optional.dependencies: >-
    python=$(python.version)
    mpmath
    numpy
    scipy
    gmpy2
    matplotlib>=2.2
    theano
    llvmlite
    autowrap
    cython
    wurlitzer
    python-symengine=0.3.*
    tensorflow
    numexpr
    ipython
    antlr-python-runtime>=4.7,<4.8
    antlr>=4.7,<4.8
    cloudpickle
    gcc

jobs:

- job: 'Doctests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        pypy: "false"
      Python34:
        python.version: '3.4'
        pypy: "false"
      Python35:
        python.version: '3.5'
        pypy: "false"
      Python36:
        python.version: '3.6'
        pypy: "false"
      Python37:
        python.version: '3.7'
        pypy: "false"
      PyPy:
        python.version: 'none'
        pypy: "true"

  steps:
  - task: UsePythonVersion@0
    condition: ne('$(pypy)', 'true')
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      virtualenv -p /usr/bin/pypy ~/.venv;
      . ~/.venv/bin/activate
    condition: eq('$(pypy)', 'true')
    displayName: 'Create PyPy virtualenv'

  - script: python -m pip install --upgrade pip && pip install mpmath
    displayName: 'Install dependencies'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'doctests'
    env:
      TEST_DOCTESTS: "true"

- job: 'Tests_split_1_2'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python34:
        python.version: '3.4'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install mpmath
    displayName: 'Install dependencies'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'tests'
    env:
      TEST_SYMPY: "true"
      SPLIT: "1/2"


- job: 'Tests_split_2_2'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python34:
        python.version: '3.4'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install mpmath
    displayName: 'Install dependencies'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'tests'
    env:
      TEST_SYMPY: "true"
      SPLIT: "2/2"

- job: 'Optional_dependencies'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  # Remove this when https://github.com/Microsoft/vsts-tasks/issues/8299 is
  # fixed.
  - script: sudo install -d -m 0777 /usr/envs
    displayName: Fix Conda permissions

  - task: CondaEnvironment@0
    inputs:
      createCustomEnvironment: true
      createOptions: "-c conda-forge"
      environmentName: 'optional-dependencies'
      packageSpecs: $(conda.optional.dependencies)
    displayName: 'Create conda environment'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'optional dependencies tests'
    env:
      TEST_ASCII: "true"
      TEST_OPT_DEPENDENCY: $(conda.optional.dependencies)
      CPATH: $CONDA_PREFIX/include
      LIBRARY_PATH: $CONDA_PREFIX/lib
      LD_LIBRARY_PATH: $CONDA_PREFIX/lib
      SYMPY_STRICT_COMPILER_CHECKS: 1

- job: 'Sage_tests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  # Remove this when https://github.com/Microsoft/vsts-tasks/issues/8299 is
  # fixed.
  - script: sudo install -d -m 0777 /usr/envs
    displayName: Fix Conda permissions


  - task: CondaEnvironment@0
    inputs:
      createCustomEnvironment: true
      createOptions: "-c conda-forge"
      environmentName: 'sage'
      packageSpecs: sage mpmath ipython>=5.5.0,<6 python=3
    displayName: 'Create conda environment'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'Sage tests'
    env:
      TEST_SAGE: "true"
      AZURE: "true"
      # remove once https://github.com/Microsoft/vsts-tasks/issues/8504 is fixed
      SAGE_ROOT: "/usr/envs/sage/"
      SAGE_LOCAL: "/usr/envs/sage/"
