# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  conda.optional.dependencies: >-
    python=$(python.version)
    mpmath
    numpy
    scipy
    gmpy2
    matplotlib>=2.2
    theano
    llvmlite
    autowrap
    cython
    wurlitzer
    python-symengine=0.3.*
    tensorflow
    numexpr
    ipython
    antlr-python-runtime>=4.7,<4.8
    antlr>=4.7,<4.8
    cloudpickle

jobs:

- job: 'Doctests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install mpmath
    displayName: 'Install dependencies'

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'doctests'
    env:
      TEST_DOCTESTS: "true"

- job: 'Optional_dependencies'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
    maxParallel: 2

  steps:
  # Remove this when https://github.com/Microsoft/vsts-tasks/issues/8299 is
  # fixed.
  - script: sudo install -d -m 0777 /usr/envs
    displayName: Fix Conda permissions

  - task: CondaEnvironment@0
    inputs:
      createCustomEnvironment: true
      createOptions: "-c conda-forge"
      environmentName: 'optional-dependencies'
      packageSpecs: $(conda.optional.dependencies)

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'optional dependencies tests'
    env:
      TEST_ASCII: "true"
      TEST_OPT_DEPENDENCY: $(conda.optional.dependencies)
      CPATH: $CONDA_PREFIX/include
      LIBRARY_PATH: $CONDA_PREFIX/lib
      LD_LIBRARY_PATH: $CONDA_PREFIX/lib
      SYMPY_STRICT_COMPILER_CHECKS: 1

- job: 'Sage_tests'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 1

  steps:
  # Remove this when https://github.com/Microsoft/vsts-tasks/issues/8299 is
  # fixed.
  - script: sudo install -d -m 0777 /usr/envs
    displayName: Fix Conda permissions


  - task: CondaEnvironment@0
    inputs:
      createCustomEnvironment: true
      createOptions: "-c conda-forge"
      environmentName: 'sage'
      packageSpecs: sagelib mpmath ipython>=5.5.0,<6

  - script: |
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py -q install;
      pip list --format=columns;
    displayName: 'Install SymPy'

  - script: |
      ./bin/test_travis.sh
    displayName: 'Sage tests'
    env:
      TEST_SAGE: "true"
      AZURE: "true"
